### ISSUE TITLE
The display does not update when selecting certain receptors.

### ISSUE THREAD

**Issue by Huitzilo** [dedan/odor_app#6]
Steps to reproduce
1 start app
2 select Gr21a, method 'all' 
3 observe that the display does not change

Further, when trying to select another method with Gr21a (e.g. 'haddad'), the Method selector freezes - no more selections are possible, also for other receptors that used to work.

I tried to debug, but on the python side everything looks fine. Can you look in the js scripts, if something's going wrong there?

Best,

Michael

**Comment by dedan** [comment]
Hey Micha,

I'll have a look at it within the next few days. Thanks for reporting

stephan

**Comment by dedan** [comment]
should be fixed by above commit

**Comment by Huitzilo** [comment]
Thanks for fixing!
On 2 Apr 2014, at 15:45, Stephan Gabler notifications@github.com wrote:

> Closed #6.
> 
> —
> Reply to this email directly or view it on GitHub.

Dr. Michael Schmuker
Freie Universität Berlin
Biomachinelearning | http://biomachinelearning.net 
Neuroinformatics   | http://fu-berlin.de/neuroinformatik
